eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 0
spring:
    application:
        name: order-server

    data:
      mongodb:
          host: localhost
          port: 27017
          database: OrderDb
          username: admin
          password:
            - password

